name = "Opus"
uuid = "0af1e411-0638-4d6d-bb05-ed1900b440d5"
version = "1.0.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Ogg = "796d8c31-69d0-5366-9081-a3bf997f4f0d"
Opus_jll = "91d4177d-7536-5919-b921-800302f37372"

[compat]
julia = "1.3"
Ogg = "1"

[extras]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DSP", "FFTW"]
